version: "3.7"

services:
  web:
    image: graphql
    container_name: graphql_web
    volumes:
      - .:/app
      - node_modules: /app/node_modules
      - db:/db
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid &&
      bundle check || bundle install &&
      yarn install &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - webpack

  webpack:
    image: graphql
    container_name: graphql_webpack
    ports:
      - "3035:3035"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: >
    sh -c './bin/webpack-dev-server'
    
volumes:
  db:
  node_modules:
